# Generated by Django 5.2.1 on 2025-05-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homelink_homesublink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='credit_cards_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='crypto_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='p2p_page',
        ),
    ]
