# Generated by Django 5.2.1 on 2025-05-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_credit_cards_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='brand_name',
            field=models.CharField(default='AWEPAY', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_prefix',
            field=models.CharField(default='Welcome to', max_length=100),
        ),
    ]
