# Generated by Django 5.2.1 on 2025-05-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_brand_name_homepage_welcome_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='welcome_prefix',
            field=models.CharField(blank=True, default='Welcome to', max_length=100),
        ),
    ]
