# Generated by Django 5.2.1 on 2025-06-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homelink_icon_class_homelink_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelink',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this main link on the homepage?'),
        ),
        migrations.AddField(
            model_name='homesublink',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this sub link on the homepage?'),
        ),
    ]
