# Generated by Django 5.2.1 on 2025-05-20 05:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_remove_bitfinexpayinsectionpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subsectionpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tabpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
