# Generated by Django 5.2.1 on 2025-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_sectionpage_body_alter_subsectionpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='is_code',
            field=models.BooleanField(default=True, help_text='是否是代码内容（会转义显示）'),
        ),
        migrations.AddField(
            model_name='subsectionpage',
            name='is_code',
            field=models.BooleanField(default=True, help_text='是否是代码内容（会转义显示）'),
        ),
    ]
