# Generated by Django 5.2.1 on 2025-05-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_sectionpage_is_code_subsectionpage_is_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='is_code',
            field=models.BooleanField(default=True, help_text='show code'),
        ),
        migrations.AlterField(
            model_name='subsectionpage',
            name='is_code',
            field=models.BooleanField(default=True, help_text='is show code?'),
        ),
    ]
