# Generated by Django 5.2.1 on 2025-05-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_sectionpage_is_code_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomeindexpage',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awesomeindexpage',
            name='nav_parent',
            field=models.ForeignKey(blank=True, help_text='if no setting, it will auto become a dropdwon menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='awesomeindexpage',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bitfinexindexpage',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bitfinexindexpage',
            name='nav_parent',
            field=models.ForeignKey(blank=True, help_text='if no setting, it will auto become a dropdwon menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='bitfinexindexpage',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creditcardsindexpage',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditcardsindexpage',
            name='nav_parent',
            field=models.ForeignKey(blank=True, help_text='if no setting, it will auto become a dropdwon menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='creditcardsindexpage',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='p2pindexpage',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p2pindexpage',
            name='nav_parent',
            field=models.ForeignKey(blank=True, help_text='if no setting, it will auto become a dropdwon menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='p2pindexpage',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
    ]
