# Generated by Django 5.2.1 on 2025-05-23 07:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_awesomeindexpage_is_dropdown_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoindexpage',
            name='code_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cryptoindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='cryptoindexpage',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptoindexpage',
            name='nav_parent',
            field=models.ForeignKey(blank=True, help_text='if no setting, it will auto become a dropdwon menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='cryptoindexpage',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
    ]
